*** Standard JavaScript Type Definitions for the HaXe Programming Language.	

This includes all HTML specifications plus all the new HTML5 technologies such as WebGL, 2D Canvas, 
WebSockets, Web Workers, HTML5 Markup Specifications, etc... 

*IMPORTANT*: /This HaXeLib does not include all the Native JavaScript implementations of (Array, Number, Boolean, 
RexExp, Error) but instead of having to replace your standard HaXe Library you can instead use the "stdjs" HaXeLib 
and Gain acess to the full HTML5 specifications stictly typedin your prefered HaXe Coding IDE or TextEditor (For 
example HaXe support in FDT)./

For usage do look at the CommonJS.hx file included in the HaxeLib for examples. More demos will bewill be added soon. 
Documentation is via the W3C specifications or you can simple view the source of the HaXelib. 

To install simply use HaXelib. run the following command after installing HaXelib, to find out more visit 
[[http://haxe.org/doc/haxelib/using_haxelib]]. In the command line simply use the follow command  
"*haxelib install xirsys_stdjs*" and then add it to your HaXe project file as a libary.

Also please post a issue if there are missing features or any other issues [[https://github.com/xirsys/stdjs/issues]] 
and we will quickly look at update the HaXelib so we can make sure it is feature complete. 

Release credited to James Jackson (jamesbjackson) and Nathan (webr3)